name: Keep Services Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # More frequent
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Frontend
        run: curl -s -o /dev/null -w "%{http_code}" https://deep-learning-project-2-3.onrender.com/

      - name: Ping Backend Model Endpoint
        run: curl -s -o /dev/null -w "%{http_code}" https://deep-learning-project-2.onrender.com/predict
