name: Keep Services Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping frontend
        run: curl -s https://deep-learning-project-2-3.onrender.com/ > /dev/null
      - name: Ping backend
        run: curl -s https://deep-learning-project-2.onrender.com/ > /dev/null
